services:
  db:
    image: mysql
    restart: always
    volumes:
      
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    # (this is just an example, not intended to be a production configuration)