services:
  db:
    ports:
      - "3306:3306/tcp"
    image: mysql
    restart: always
    volumes:
      - ${MSQLCONFPATH}:/etc/mysql/conf.d
      - ${MSQLDATAPATH}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPASS}
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DBUSER}
      MYSQL_PASSWORD: ${DBPASS}
